Add numParallelCollections and viewsAsCollections options
boly38/node-mongotools pull request #51
Opened 2022-07-08 11:12 UTC by chdanielmueller

per https://www.mongodb.com/docs/v4.2/reference/program/mongodump/#mongodump-options

2022-07-08 11:34 UTC, boly38 requested changes
welcome @chdanielmueller and thanks for your contribution 👍 

could you 
- put 2 more row in [readme mongodump options](https://github.com/boly38/node-mongotools#mongodump-options)
- create an issue and refer to it in your single commit msg please 🙏 (in fact the automated release process will include issues only to create release [notes](https://github.com/boly38/node-mongotools/releases))

2022-07-08 11:41 UTC, chdanielmueller commented
Options are now documented and issue is open and referenced in the PR and commit message

2022-07-08 14:34 UTC, boly38 commented on README.md
> +| `excludeCollections`     |           | false    | false                   | When specified, mongodump exports read-only views as collections.     |
`viewsAsCollections`

2022-07-11 09:36 UTC, boly38 approved these changes
LGTM
squash is recommended but not enforced.

with ou without squash I ll merge it in about 2h

2022-07-11 10:42 UTC, chdanielmueller commented
You can do a squash merge if you want.
Happy you found my contribution worth to merge.
Thanks for taking the time to look at it

2022-07-11 11:34 UTC, boly38 approved these changes

2022-07-11 11:35 UTC, merged